### ISSUE TITLE
To create an application using rest client.

### ISSUE THREAD

**Issue by securelord** [openshift/openshift-java-client#246]
How can I create an application using the rest client?
Here's how it's done in the Eclipse plugin.

**Comment by adietish** [comment]
Hi

please notice that this client library for OpenShift 2 is not actively maintained any more since all development efforts moved over to the OpenShift 3.
Nevertheless, in order to point you to point the code that's creating an application with this library please have a look at https://developer.jboss.org/wiki/Enable-openshift-ciFullExampleUsingOpenshift-java-client
The sequence of commands is ~ the following (not tested, pasted freely from the example):
```
IOpenShiftConnection connection =
				new OpenShiftConnectionFactory()
						.getConnection("my_example_client", user, password, new OpenShiftConfiguration().getLibraServer());
IUser user = connection.getUser();
IDomain domain = user.getDefaultDomain();
if (domain == null) {
		domain = user.createDomain("my_domain");
}
IApplication application = domain.createApplication("my_application", ICartridge.JBOSSAS_7);
```
